version: '3'
services:

  fakeimages.laravel.api:
    build:
      dockerfile: Dockerfile_api
      context: ./backend/laravel
    container_name: fakeimages.laravel.api
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    networks:
      - fake_images
    depends_on:
      - mysql
      - redis

  fakeimages.laravel.jobs:
    build:
      dockerfile: Dockerfile_job
      context: ./backend/laravel
    container_name: fakeimages.laravel.jobs
    env_file:
      - ./.env
    networks:
      - fake_images
    depends_on:
      - mysql
      - redis


  mysql:
    build:
      dockerfile: ./services/mysql/Dockerfile
      context: .
    container_name: mysql
    volumes:
      - ./volumes/db/mysql/main:/var/lib/mysql
    env_file:
      - .env
    ports:
      - '3306:3306'
    networks:
      - fake_images

  redis:
    build:
      dockerfile: ./services/redis/Dockerfile
      context: .
    container_name: redis
    volumes:
      - ./volumes/db/redis/cache:/data
    ports:
      - '6379:6379'
    networks:
      - fake_images

  nginx.router:
    build:
      dockerfile: ./services/nginx/Dockerfile
      context: .
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
    networks:
      - fake_images
    depends_on:
      - fakeimages.laravel.api
      - fakeimages.laravel.jobs
      - redis
      - mysql

networks:
  fake_images:
    driver: bridge
