version: '3'
services:
# Вариант - когда часть функционала я выношу в отдельный микросервис
# очень оправдан для фоновых задач, но может нанести вред для запросов
#  fakeimages.laravel.api.auth:
#    build:
#      dockerfile: Dockerfile_api
#      context: ./backend/laravel
#    container_name: fakeimages.laravel.api.auth
#    env_file:
#      - ./.env
#    networks:
#      - fake_images
#    depends_on:
#      - mysql
#      - redis

#  fakeimages.laravel.api:
#    build:
#      dockerfile: Dockerfile_api
#      context: ./backend/laravel
#    container_name: fakeimages.laravel.api
#    ports:
#      - '8000:8000'
#    env_file:
#      - ./.env
#    networks:
#      - fake_images
#    depends_on:
#      - mysql
#      - redis


# -------------------------------------------------------------
# Вариант, когда 1 сервер не справляется с задачами - я могу создать 2-3 и тд серверов
# по факту - копий исходного сервиса. И случайным образом распределить между ними нагрузку
  fakeimages.laravel.api.sunny:
    build:
      dockerfile: Dockerfile_api
      context: ./backend/laravel
    container_name: fakeimages.laravel.api.sunny
    env_file:
      - ./.env
    networks:
      - fake_images
    depends_on:
      - mysql
      - redis
  fakeimages.laravel.api.jonny:
    build:
      dockerfile: Dockerfile_api
      context: ./backend/laravel
    container_name: fakeimages.laravel.api.jonny
    env_file:
      - ./.env
    networks:
      - fake_images
    depends_on:
      - mysql
      - redis
# -------------------------------------------------------------

# Ведение фоновых задач в отдельном микросервисе практически всегда оправдывает себя
# с помощью управления очередями я могу еще и по типам вести задачи
  fakeimages.laravel.jobs:
    build:
      dockerfile: Dockerfile_job
      context: ./backend/laravel
    container_name: fakeimages.laravel.jobs
    env_file:
      - ./.env
    networks:
      - fake_images
    depends_on:
      - mysql
      - redis


  mysql:
    build:
      dockerfile: ./services/mysql/Dockerfile
      context: .
    container_name: mysql
    volumes:
      - ./volumes/db/mysql/main:/var/lib/mysql
    env_file:
      - .env
    ports:
      - '3306:3306'
    networks:
      - fake_images

  redis:
    build:
      dockerfile: ./services/redis/Dockerfile
      context: .
    container_name: redis
    volumes:
      - ./volumes/db/redis/cache:/data
    ports:
      - '6379:6379'
    networks:
      - fake_images

  nginx.router:
    build:
      dockerfile: ./services/nginx/Dockerfile
      context: .
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
    networks:
      - fake_images
    depends_on:
      # - fakeimages.laravel.api.auth
      # - fakeimages.laravel.api
      - fakeimages.laravel.api.jonny
      - fakeimages.laravel.api.sunny
      - fakeimages.laravel.jobs
      - redis
      - mysql

networks:
  fake_images:
    driver: bridge
